# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b4a88915682b08563e6237735c9f37edd0789a0ffbd34af8a2cdbc0fd67593cf4771bdb6bc240019fe8a8cb510c0f748f2831886c24226384b1d4bb2f56ec5d

test:
  secret_key_base: b4492f66d0dc4f681431863105efdbfdcbd19720f98f4abaaec41eaca35690535d85c62ca196c2cce42178bbcde0683eb56fc920d0af81204297c13d3192f52b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
